version: "3.9"
services:
  db:
    image: postgres:15.1-alpine
    container_name: my-db
    restart: always
    volumes:
      - weatherly:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: my-db
      POSTGRES_USER: my-db
      POSTGRES_PASSWORD: my-db-password
    ports:
      - 5432:5432
volumes:
    weatherly: